
set head off
set pages 0
set long 9999999
spool user_script.sql


SELECT password FROM SYS.USER$ WHERE name = 'RM';

SELECT DBMS_METADATA.GET_DDL('USER', 'RM') || '/' DDL FROM DBA_USERS
UNION ALL
SELECT DBMS_METADATA.GET_GRANTED_DDL('ROLE_GRANT', 'RM') || '/' DDL FROM DBA_USERS
UNION ALL
SELECT DBMS_METADATA.GET_GRANTED_DDL('SYSTEM_GRANT', 'RM') || '/' DDL FROM DBA_USERS
UNION ALL
SELECT DBMS_METADATA.GET_GRANTED_DDL('OBJECT_GRANT', 'RM') || '/' DDL FROM DBA_USERS;

spool off;
